# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        # Don't fail the check if patch coverage is above 80%
        informational: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
